cancel:
  name: Cancel
  description: Cancel the current program.

start_keep_warm:
  name: Start Keep Warm
  description: Start Keep Warm with either a temperature (°C) or a preset.
  fields:
    temp_c:
      name: Temperature (°C)
      description: Provide either Temperature OR Preset (leave the other blank).
      selector:
        number:
          min: 25
          max: 95
          step: 1
          mode: box
    preset:
      name: Preset
      description: Provide either Temperature OR Preset.
      selector:
        select:
          options:
            - Low
            - High
          mode: dropdown
    duration:
      name: Duration
      description: Total duration
      selector:
        duration: {}

update_keep_warm:
  name: Update Keep Warm
  description: Update Keep Warm settings (any subset).
  fields:
    temp_c:
      name: Temperature (°C)
      selector:
        number:
          min: 25
          max: 95
          step: 1
          mode: box
    preset:
      name: Preset
      selector:
        select:
          options: [Low, High]
          mode: dropdown
    duration:
      name: Duration
      selector:
        duration: {}

start_pressure_cook:
  name: Start Pressure Cook
  description: Start Pressure Cook with desired settings.
  fields:
    pressure:
      name: Pressure
      selector:
        select:
          options: [Low, High, Max]
    cook_time:
      name: Cook Time
      selector:
        duration: {}
    venting:
      name: Venting
      selector:
        select:
          options: [Natural, Pulse, Quick, NaturalQuick]
          mode: dropdown
    vent_time:
      name: Venting Time (optional)
      selector:
        duration: {}
    nutriboost:
      name: NutriBoost
      selector:
        boolean: {}

update_pressure_cook:
  name: Update Pressure Cook
  description: Update any subset of Pressure Cook settings.
  fields:
    pressure:
      name: Pressure
      selector:
        select:
          options: [Low, High, Max]
    cook_time:
      name: Cook Time
      selector:
        duration: {}
    venting:
      name: Venting
      selector:
        select:
          options: [Natural, Pulse, Quick, NaturalQuick]
    vent_time:
      name: Venting Time
      selector:
        duration: {}
    nutriboost:
      name: NutriBoost
      selector:
        boolean: {}

